baseurl:  /inspireFramework
relative_permalinks: true
permalink: name
excerpt_separator: ""
pygments: true
markdown: maruku

#
# Site-Specific Settings  
#
name: "inspireFramework"
tagline: For Building Awesome Sites!
description: ''
